// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '按钮': typeof import('./src/components/按钮.vue')['default']
    '菜单': typeof import('./src/components/菜单.vue')['default']
    '菜单重写': typeof import('./src/components/菜单重写.vue')['default']
    '内容': typeof import('./src/components/内容.vue')['default']
    '首行': typeof import('./src/components/首行.vue')['default']
    '添加订单窗口': typeof import('./src/components/添加订单窗口.vue')['default']
    '头部': typeof import('./src/components/头部.vue')['default']
    '行': typeof import('./src/components/行.vue')['default']
    '用户首行': typeof import('./src/components/用户首行.vue')['default']
    '用户行': typeof import('./src/components/用户行.vue')['default']
    copy: typeof import('./src/components/行 copy.vue')['default']
    ElButten: typeof import('element-plus/es')['ElButten']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Icon: typeof import('./src/components/icons/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
